feat: add Login screen and navigation between screens
sarahrubia/mobile pull request #2
Opened 2022-10-04 19:49 UTC by sarahrubia

## O quê
Adiciona tela de login e navegação entre telas

## Porque
Faz parte do Onboarding no time Confia.

## Como
- Criar um componente de tela para Login
- Adicionar navegação com React Navigation

## Amostra

### iOS

**iPhone 14**

<img src="https://user-images.githubusercontent.com/52300436/193911652-30e2084e-c410-4a6b-a8e2-3f3ae0eff928.png" width="360">

<img src="https://user-images.githubusercontent.com/52300436/193911771-1611e1a6-3d5f-41b5-a956-54a028335f7b.png" width="360">

<img src="https://user-images.githubusercontent.com/52300436/193911868-a4d75164-c0b6-4e33-bdb7-3be863c95250.png" width="360">

2022-10-05 15:15 UTC, lucianomlima requested changes
O objetivo das imagens `@2x` e `@3x` é terem a mesma qualidade em telas que tem uma densidade de pixel alta. E por causa disso, elas precisam ter respectivamente o dobro e o triplo da resolução da imagem padrão. Então sugiro rever as imagens e ajustar para que elas tenham a qualidade esperada em dispositivos com telas de alta densidade de pixels.

Notei que tem mais de 1 tipo de ícone `eye`. Remova o que não estiver sendo utilizado.

Faltou remover os arquivos de fonte do iOS.

2022-10-05 15:15 UTC, lucianomlima commented on package.json
> +    "@types/react-native-vector-icons": "^6.4.12",
🔧 Como você removeu o react-native-vector-icons, não se faz mais necessário ter os types aqui.

2022-10-05 15:15 UTC, lucianomlima commented on src/components/AppButton.tsx
> +const AppButton: FunctionComponent<buttonText> = ({ title, screenName }) => {
💡 Apesar de também estar correto, costumamos usar funções para declarar componentes. Então para fins de ter menor impacto ao começar a ter contato com o mobile app, faço a seguinte sugestão:
```suggestion
function AppButton({ title, screenName }: AppButtonProps) {
```

Note que tem mais alguns ajustes:
- Iniciamos nomes de tipos de componentes com a letra maiúscula
- Geralmente padronizamos o tipo com o mesmo nome do componente + sufixo `Props`

2022-10-05 15:15 UTC, lucianomlima commented on src/constants/navigation/constants.js
> +export const dashboardScreen = 'Dashboard';
💡 Aqui minha sugestão é exportar um objeto e utilizar como constante de fato:
```suggestion
export const routes = {
  LOGIN: 'login',
  HOME: 'home',
  DASHBOARD: 'dashboard',
}
```

2022-10-05 15:15 UTC, lucianomlima commented on src/routes/public.tsx
> +import { homeScreen } from '../constants/navigation/constants';
...e aqui bastaria importar o objeto (poderia também tornar o caminho mais simples)
```suggestion
import { routes } from '../constants/navigation';
```

2022-10-05 15:15 UTC, lucianomlima commented on src/routes/public.tsx
> +    </NavigationContainer>
...e aqui mudaria para
```suggestion
    <NavigationContainer>
      <Stack.Navigator
        initialRouteName={routes.HOME}
        screenOptions={{
          headerStyle: {
            backgroundColor: '#222222',
          },
          headerTintColor: '#FFF',
        }}>
        <Stack.Screen name={routes.HOME} component={HomeScreen} />
        <Stack.Screen name={routes.LOGIN} component={LoginScreen} />
      </Stack.Navigator>
    </NavigationContainer>
```

2022-10-05 15:15 UTC, lucianomlima commented on src/routes/public.tsx
> +import Login from '../screens/Login';
💡 Aqui seria legal deixar explícito que se tratam de screens
```suggestion
import HomeScreen from '../screens/Home';
import LoginScreen from '../screens/Login';
```

2022-10-05 15:15 UTC, lucianomlima commented on src/screens/Home.tsx
> +  SafeAreaView,
🔧 Aqui ficou faltando mudar o import do SafeAreaView

2022-10-05 15:15 UTC, lucianomlima commented on src/screens/Login.tsx
> +import CheckBox from '@react-native-community/checkbox';
💡 Sei que não está explícito em local algum, mas geralmente temos um padrão na ordem de importação que é:

1. Bibliotecas de terceiros (iniciando por react e react-native)
2. Importações absolutas (geralmente fora do diretório atual)
3. Importações relativas (geralmente as que estão no diretório atual ou subdiretórios)

Também tentamos separar em blocos, através da inserção de uma linha em branco, para facilitar a leitura e a identificação:
```suggestion
import React, { useState } from 'react';
import {
  Image,
  Pressable,
  StatusBar,
  StyleSheet,
  Text,
  TextInput,
  View,
} from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import CheckBox from '@react-native-community/checkbox';

import AppButton from '../components/AppButton';
```

2022-10-05 15:15 UTC, lucianomlima commented on src/screens/Login.tsx
> +  const [focusPassword, setFocusPassword] = useState(false);
🔧 Para variáveis que representam um valor booleano é interessante tentar deixar isso explícito através da nomenclatura da variável. Um exemplo seria mudar para:
```suggestion
  const [isSecureTextEntry, setSecureTextEntry] = useState(true);
  const [isEmailFocused, setEmailFocused] = useState(false);
  const [isPasswordFocused, setPasswordFocused] = useState(false);
```

2022-10-05 15:15 UTC, lucianomlima commented on src/screens/Login.tsx
> +              style={focusEmail ? styles.inputBoxOnFocus : styles.inputBox}
...assim fica mais simples ao ler o código aqui
```suggestion
              style={isEmailFocused ? styles.inputBoxOnFocus : styles.inputBox}
```

2022-10-05 15:15 UTC, lucianomlima commented on src/screens/Login.tsx
> +                )}
💡 É possível também importar as imagens antes e depois só decidir qual vai usar

Lá em cima você importa:
```ts
const EyeOpenedIcon = require('../assets/view.png');
const EyeClosedIcon = require('../assets/hide.png');
```
E depois
```suggestion
                <Image style={styles.eyeImg} source={isSecureTextEntry ? EyeOpenedIcon : EyeClosedIcon} />
```

2022-10-05 18:52 UTC, pedro-cerdera commented on src/components/AppButton.tsx
> +};
💡 
Validando o botão, percebe-se que a ideia de sua criação está corretíssima, mas ele tem um problema que é importante de se ver no momento da criação, ele limita o botão: 
- Suponha um uso em que o botão não faça a navegação, ou faça algo antes, é provável que seja necessário refatorar o botão.

Apesar disso, o racional para criar o componente está correto. Minha sugestão seria o componente receber a prop onPress e deixava a responsabilidade de decidir o que será feito no clique com a tela que o chamar.

2022-10-05 18:52 UTC, pedro-cerdera commented on src/components/AppButton.tsx
> +    marginBottom: 16,
💡 
Sempre que colocarmos uma margem envolvendo um componente, precisamos fazer isso com muita convicção que não haverá uma situação em que a margem não seja usada. Pense que muitas vezes um botão pode ter espaçamentos diferentes de acordo com o contexto da tela. Particularmente deixaria o botão sem margem e colocaria a margem numa View envolvendo o componente.

2022-10-05 18:52 UTC, pedro-cerdera commented on src/routes/public.tsx
> +        <Stack.Screen name={routes.HOME} component={HomeScreen} />
💡 
Não tenho certeza, mas acredito que a tela inicial não tem um header. Caso seja verdade, você pode usar a option headershown (https://reactnavigation.org/docs/native-stack-navigator/#headershown). 
```suggestion
        <Stack.Screen 
            name={routes.HOME} 
            component={HomeScreen} 
            options={{
              headerShown: false,
            }} />
```

2022-10-05 18:52 UTC, pedro-cerdera commented on src/screens/Home.tsx
> +const Home = () => {
💡 
Indo na mesma [linha sugerida](https://github.com/sarahrubia/mobile/pull/2#discussion_r988023459) por @lucianomlima colocaria aqui também como função. 
```suggestion
function Home() {
```

2022-10-05 18:52 UTC, pedro-cerdera commented on src/screens/Login.tsx
> +const Login = () => {
💡 
Indo na mesma [linha sugerida](https://github.com/sarahrubia/mobile/pull/2#discussion_r988023459) por @lucianomlima colocaria aqui também como função. 

```suggestion
function Login() {
```

2022-10-05 18:52 UTC, pedro-cerdera commented on src/screens/Login.tsx
> +          </View>
💡 
Aqui há uma oportunidade de criação de um componente de input que teria encapsulado esta função de focus, eliminando assim o controle destes estados pela tela e tornando responsabilidade do próprio componente. Este mesmo componente poderia ter uma prop simples como `securityMode` que seria responsável por exibir ou não a imagem do olho.

2022-10-05 21:12 UTC, lucianomlima approved these changes
Ótimo trabalho!

2022-10-05 22:39 UTC, sarahrubia commented on src/screens/Login.tsx
> +          </View>
Ótima ideia! Acho que consegui aqui: [6e45e3b](https://github.com/sarahrubia/mobile/pull/2/commits/6e45e3b8f735a61de14269db1d19ecfd51958a64). Depois adicionei o typescript [2b53211](https://github.com/sarahrubia/mobile/pull/2/commits/2b53211c73fdfd61709e550064bcc8c08016b7be).

2022-10-05 22:51 UTC, sarahrubia commented on src/components/AppButton.tsx
> +};
Feito! [9d24891](https://github.com/sarahrubia/mobile/pull/2/commits/9d24891d1bc8fd719f83eede67e70909aefbb7a9)

2022-10-06 11:32 UTC, lucianomlima commented on src/components/AppButton.tsx
> +  onPress?: any;
❓Por que o botão com `onPress` opcional? Alguma razão em específico para um botão ser usado sem ter a ação que será chamada ao ser pressionado?

🔧Evitar uso de any. Nesse caso, o `onPress` será sempre uma função e deve ser topada como tal.

2022-10-06 11:32 UTC, lucianomlima commented on src/components/InputField.tsx
> +};
💡 Você pode reutilizar os types que já são definidos nessas props do próprio React Native.

2022-10-06 11:32 UTC, lucianomlima commented on src/components/InputField.tsx
> +  securityMode,
💡 Você pode usar a própria prop `secureTextEntry` para decidir sobre exibir ou não a parte do ícone do olho.

2022-10-06 11:52 UTC, sarahrubia commented on src/components/AppButton.tsx
> +  onPress?: any;
Eu coloquei opcional só enquanto não decidia a função para o botão da tela de Login. Como defino o tipo para função, @lucianomlima?

2022-10-06 12:33 UTC, sarahrubia commented on src/components/InputField.tsx
> +  securityMode,
Fiz as alterações a partir das sugestões ([0f9ef8e](https://github.com/sarahrubia/mobile/pull/2/commits/0f9ef8e9bfab85e1028a2c9554f4b013732751a6)). 

Pesquisei sobre como tipar função pra remover o "any" do onPress, mas ainda não entendi como fazer 😅

2022-10-06 13:33 UTC, lucianomlima commented on src/components/AppButton.tsx
> +  onPress: ((event: GestureResponderEvent) => void) | undefined;
🔧 Infelizmente não está correto 😅. Na verdade basta definir como uma função sem parâmetros mesmo. Sei que é confuso por que o react native permite criar um botão que não tenha onPress e que receba um evento como parâmetro, mas no dia a dia só precisamos declarar parâmetros caso a função espere isso.
```suggestion
  onPress: () => void;
```

2022-10-06 13:33 UTC, lucianomlima commented on src/components/InputField.tsx
> +  secureTextEntry?: boolean | undefined;
💡 Quando for o caso de usar exatamente as mesmas props, você tem duas possibilidades:
1. Importar a prop diretamente do react native e usar como suas props:
```
import { TextInputProps } from 'react-native'
...
function InputField({
  placeholder,
  placeholderTextColor,
  secureTextEntry,
}: TextInputProps) {
```
2. Ou extender suas props a partir do type importado do react native:
```ts
interface InputFieldProps extends TextInputProps;
ou
type InputFieldProps = TextInputProps;
```
A segunda opção geralmente usamos quando precisamos adicionar custom props ou mudar o type de alguma prop original. Dessas duas formas, você usa o mesmo type definido no react native, o que é melhor no longo prazo, já que se houver alguma alteração, seu type acompanha a mudança, evitando que seja necessário fazer altertação no código por causa disso.

2022-10-06 13:33 UTC, lucianomlima commented on src/components/InputField.tsx
> +  secureTextEntry,
💡 Usando a prop original do react native, se faz desnecessário ter um state

2022-10-06 13:33 UTC, lucianomlima commented on src/screens/Login.tsx
> +              secureTextEntry={false}
🔧 Como o valor default dessa prop é false, não há necessidade de declarar ela no componente.
```suggestion
```

2022-10-06 13:33 UTC, lucianomlima commented on src/screens/Login.tsx
> +              secureTextEntry={true}
💡 Quando uma prop for boolean, você pode simplesmente apenas declarar ela para que ela assuma o valor true
```suggestion
              secureTextEntry
```

2022-10-06 13:33 UTC, lucianomlima commented on src/screens/Login.tsx
> +        <AppButton title={'ENTRAR'} onPress={() => console.log('Login')} />
❓ Mudou aqui?

2022-10-06 14:25 UTC, sarahrubia commented on src/components/AppButton.tsx
> +  onPress: ((event: GestureResponderEvent) => void) | undefined;
poxa! 🤣

2022-10-06 14:34 UTC, sarahrubia commented on src/screens/Login.tsx
> +        <AppButton title={'ENTRAR'} onPress={() => console.log('Login')} />
Mudei apenas para não deixar o onPress como opcional xD

2022-10-06 14:59 UTC, lucianomlima commented on src/screens/Login.tsx
> +        <AppButton title={'ENTRAR'} onPress={() => console.log('Login')} />
Aí o ideal é colocar a chamada de navegação mesmo 😉

2022-10-06 15:07 UTC, sarahrubia commented on src/components/InputField.tsx
> +  secureTextEntry,
Removi o state para o secureTextEntry e adicionei um state chamado securityMode, que vai controlar se a senha está visível ou não a partir do clique no olhinho. 

Sem o state, não consigo mudar a senha para visível e não-visível apenas a partir do secureTextEntry. Tentei adicionar um `onPress={() => !secureTextEntry}` no botão, mas não funciona (talvez porque a mudança não fica salva em um estado que pode ser alterado?). 

[a4183bd](https://github.com/sarahrubia/mobile/pull/2/commits/a4183bdd0eaeb1c9cafd47ead11afa644597ecea)

2022-10-06 17:03 UTC, lucianomlima commented on src/components/InputField.tsx
> +  secureTextEntry,
Boa! Bem observado!

2022-10-06 17:09 UTC, lucianomlima commented on src/screens/Login.tsx
> +  const navigation = useNavigation();
🔧 As telas já tem acesso a prop navigation automaticamente. Mas você pode ajeitar isso no próxima atividade 😉

2022-10-06 17:22 UTC, pedro-cerdera approved these changes

2022-10-06 17:41 UTC, merged