refactor: refactor StyleSheet using Styled Components
sarahrubia/mobile pull request #3
Opened 2022-10-11 14:46 UTC by sarahrubia

## O quê
Instalar a biblioteca [styled-components](https://styled-components.com/docs/basics#installation) e refatorar as telas de login e inicial removendo o uso do stylesheet.

## Porque
Faz parte do Onboarding no time Confia. É bem comum em projetos as refatorações de código. A ideia é mostrar do que se trata este tipo de atividade.

## Como
- Instalar a biblioteca Styled Components
- Refatorar o código das telas Login e Home.

2022-10-11 20:21 UTC, lucianomlima commented on package.json
> +    }
❓ Por que foi necessário adicionar um resolutions?

2022-10-11 20:21 UTC, lucianomlima commented on package.json
> +    "styled-components": "^5"
❓ Qual a necessidade de ter esse resolutions aqui?

2022-10-11 20:21 UTC, lucianomlima commented on src/routes/public.tsx
> +import LoginScreen from '../screens/login/Login';
💡 Aqui é mais interessante que os diretórios tenham o mesmo nome que os componentes
```suggestion
import HomeScreen from '../screens/Home/Home';
import LoginScreen from '../screens/Login/Login';
```
Caso queira diminuir a repetição, pode ter um arquivo index que exporte os componentes.

2022-10-11 20:21 UTC, lucianomlima commented on src/screens/login/styled.ts
> +`;
🔧 Dessa forma você voltou a utilizar o SafeAreaView do RN. Precisa garantir que seja o `SafeAreaView` do `react-native-safe-area-context`

2022-10-11 20:21 UTC, lucianomlima commented on src/screens/login/styled.ts
> +export const BtnWrapper = styled.View`
💡 Aqui ficaria mais expressivo se no nome aproveitar a responsabilidade do botão:
```suggestion
export const SubmitButtonWrapper = styled.View`
```
Poderia ser `Container` também. Não precisa também abreviar o nome dos componentes. Explícito é melhor que implícito.

ref: [1.1 Meaningful and Pronounceable Variables](https://medium.com/coders-equity/a-complete-guide-to-clean-code-principles-for-javascript-82052c317789#ad84)

2022-10-11 20:21 UTC, lucianomlima commented on src/screens/login/Login.tsx
> +import { routes } from '../../constants/navigation/constants';
⛏️ Sempre bom manter as importações locais após as importações externas
```suggestion
import AppButton from '../../components/AppButton';
import InputField from '../../components/InputField';
import { routes } from '../../constants/navigation/constants';

import * as S from './styled';
```

2022-10-11 20:21 UTC, lucianomlima commented on src/screens/login/Login.tsx
> +          </S.TitleText>
💡 Se o componente não deixa dúvida sobre o que ele é, não há necessidade de enfatizar isso. `Title` é subentendido que seja um texto. E como M-Pay parece ser o nome da empresa, poderia ser nomeado como tal
```suggestion
          <S.Title>
            Entrar <S.CompanyName>M-PAY</S.CompanyName>
          </S.Title>
```

2022-10-11 20:21 UTC, lucianomlima commented on src/screens/login/Login.tsx
> +          <S.MarginView>
⛏️ Esse componente não ajuda a entender o que ele faz, além de deixar implícito que tem uma margem. Como está sendo usado sempre como container do input, pode ser nomeado como tal (e nesse cenário, o espaçamento estar implícito não é um problema).
```suggestion
          <S.TextInputContainer>
```
Também deixaria explícito que é um TextInput, por que podemos ter inputs específicos para outros tipos de dados como número, senha, URL, etc. E especialização geralmente escala melhor do que super generalização (um componente ser usado para vários cenários).

2022-10-11 20:21 UTC, lucianomlima commented on src/screens/onboarding/Home.tsx
> +          <S.SmallText>M-Pay: A Melhor carteira digital do mundo!</S.SmallText>
💡 Tentaria usar mais o que cada texto representa, ao invés de suas características

2022-10-13 13:30 UTC, pedro-cerdera requested changes

2022-10-13 13:30 UTC, pedro-cerdera commented on src/screens/login/Login.tsx
> +              }}
💡 
Acho que este componente também poderia estar com os estilos no styled components. Assim evitaria ignorar a regra

2022-10-13 13:30 UTC, pedro-cerdera commented on src/screens/onboarding/styled.ts
> +export const BtnWrapper = styled.View`
💡 
Mesmo que o mencionado aqui https://github.com/sarahrubia/mobile/pull/3/files#r992546344

2022-10-13 16:12 UTC, sarahrubia commented on package.json
> +    }
Conforme a documentação do [styled components](https://styled-components.com/docs/basics#installation)

> If you use a package manager like [yarn](https://yarnpkg.com/) that supports the "resolutions" package.json field, we also highly recommend you add an entry to it as well corresponding to the major version range. This helps avoid an entire class of problems that arise from multiple versions of styled-components being installed in your project.

Acabei instalando só pela sugestão na documentação, mas como não usei mais de uma versão do Styled Components, imagino que posso remover o resolutions.

2022-10-13 16:42 UTC, sarahrubia commented on src/screens/login/styled.ts
> +`;
Resolvido aqui: [820df25](https://github.com/sarahrubia/mobile/pull/3/commits/820df25cb6ec61d3ae6163b8b5df44e05f46cfa5)

2022-10-13 17:07 UTC, sarahrubia commented on src/screens/login/Login.tsx
> +              }}
O CheckBox é um componente importado do react-native-community. Eu tentei importá-lo na página de estilos `styled.ts` e adicionar o styled components diretamente nele, mas não funciona. 

Como o styled components cria, de fato, um componente, eu também não consegui adicioná-lo dentro da tag style (onde o estilo funciona), ex: `style={ S.Checkbox }`

A única forma que encontrei de mantê-lo estilizado foi assim como está. Você tem alguma sugestão, @pedro-cerdera?

2022-10-13 17:09 UTC, sarahrubia commented on src/screens/onboarding/Home.tsx
> +          <S.SmallText>M-Pay: A Melhor carteira digital do mundo!</S.SmallText>
Todas as questões referentes a variáveis foram resolvidas nesse commit [ea97b71](https://github.com/sarahrubia/mobile/pull/3/commits/ea97b7131727b706e8fe391477ff98ac52d65906)

2022-10-13 17:20 UTC, sarahrubia commented on package.json
> +    "styled-components": "^5"
Removido [3ee182d](https://github.com/sarahrubia/mobile/pull/3/commits/3ee182d296ec196d7ea51448216497214d12a811)

2022-10-14 01:16 UTC, lucianomlima commented on package.json
> +    }
Certo. Esse caso que a documentação fala (mas não explica) é quando você decide instalar algum pacote de componentes que foram feitos com styled-components mas uma versão diferente da que é usada no projeto. Nesse cenário, pode ocorrer o caso de ter versões diferentes da biblioteca e ocorrer problemas de compatibilidade.

Mas esse não é o caso do seu projeto, por isso, é desnecessário 😉

2022-10-14 13:16 UTC, lucianomlima commented on package.json
> +    }
👍

2022-10-14 13:16 UTC, lucianomlima commented on package.json
> +    "styled-components": "^5"
👍

2022-10-14 13:18 UTC, lucianomlima commented on src/screens/login/styled.ts
> +`;
Não está resolvido, por que você ainda não está usando o `SafeAreaView` do `react-native-safe-area-context`. Você apenas importou, mas continua usando o do React Native.

2022-10-14 13:21 UTC, lucianomlima commented on src/routes/public.tsx
> +import LoginScreen from '../screens/login/Login';
👍

2022-10-14 13:23 UTC, lucianomlima commented on src/screens/login/styled.ts
> +export const BtnWrapper = styled.View`
👍

2022-10-14 13:24 UTC, lucianomlima commented on src/screens/login/Login.tsx
> +import { routes } from '../../constants/navigation/constants';
👍

2022-10-14 13:25 UTC, lucianomlima commented on src/screens/login/Login.tsx
> +          </S.TitleText>
👍

2022-10-14 13:25 UTC, lucianomlima commented on src/screens/login/Login.tsx
> +          <S.MarginView>
👍

2022-10-14 13:25 UTC, lucianomlima commented on src/screens/onboarding/Home.tsx
> +          <S.SmallText>M-Pay: A Melhor carteira digital do mundo!</S.SmallText>
👍

2022-10-14 13:29 UTC, lucianomlima commented on package.json
> +    "styled-components": "^5.3.6"
💡 Só para ficar aqui uma dica: evite fazer atualização de bibliotecas junto com alguma taefa de implementação. Sempre que atualizamos algo, corremos o risco de ter alguma mudança que possa causar um problema no produto.

Se faz atualização junto com modificações e apresenta um problema, fica difícil saber se foi causado pela atualização ou pela modificação. Então é sempre bom deixar alterações de tipos diferentes isoladas.

Nesse cenário, o mais indicado é separar PR por contexto:

- PR de atualização
- PR de refatoração (mudança que não impacte a usablidade)
- PR de alteração de comportamento

Assim, caso algum problema surja, fica mais fácil saber a origem, e com isso menos tempo é gasto na investigação e possível solução do problema.

2022-10-14 13:33 UTC, lucianomlima commented on src/screens/login/Login.tsx
> +              }}
Para fazer com que o styled components aplique os estilos num componente externo, basta encapsular o componente no styled:

```ts
styled(Componente)`
  estilo: valor
`;
```

Internamente o styled é uma função que aceita argumentos e faz algumas técnicas de interpolação de string para que possa ser usado num formato um pouco diferente do comum para uma função.

2022-10-14 17:24 UTC, sarahrubia commented on src/screens/login/Login.tsx
> +              }}
Pesquisando, acabei descobrindo isso. Mas não tinha uma explicação como a que você deu. Agora fez mais sentido. Obrigada, @lucianomlima!

A alteração foi feita aqui: [d3d6068](https://github.com/sarahrubia/mobile/pull/3/commits/d3d60682a4d9f9eea3357253b922d83004425a3c)

O commit corresponde também ao [comentário](https://github.com/sarahrubia/mobile/pull/3#discussion_r995752187):
> Não está resolvido, por que você ainda não está usando o `SafeAreaView` do `react-native-safe-area-context`. Você apenas importou, mas continua usando o do React Native.

2022-10-14 17:32 UTC, sarahrubia commented on src/screens/login/styled.ts
> +`;
Feito: [d3d6068](https://github.com/sarahrubia/mobile/pull/3/commits/d3d60682a4d9f9eea3357253b922d83004425a3c)

2022-10-14 18:38 UTC, pedro-cerdera approved these changes

2022-10-14 18:42 UTC, pedro-cerdera approved these changes

2022-10-14 18:46 UTC, lucianomlima commented on src/screens/login/styled.ts
> +`;
:+1:

2022-10-14 18:47 UTC, lucianomlima approved these changes

2022-10-14 18:49 UTC, merged